/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.content_ratings.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Rating service. Represents a row in the &quot;EAB_CR_Rating&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.content_ratings.model.impl.RatingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.content_ratings.model.impl.RatingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Rating
 * @see es.aragon.base.content_ratings.model.impl.RatingImpl
 * @see es.aragon.base.content_ratings.model.impl.RatingModelImpl
 * @generated
 */
@ProviderType
public interface RatingModel extends AttachedModel, BaseModel<Rating>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rating model instance should use the {@link Rating} interface instead.
	 */

	/**
	 * Returns the primary key of this rating.
	 *
	 * @return the primary key of this rating
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rating.
	 *
	 * @param primaryKey the primary key of this rating
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this rating.
	 *
	 * @return the uuid of this rating
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this rating.
	 *
	 * @param uuid the uuid of this rating
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the rating ID of this rating.
	 *
	 * @return the rating ID of this rating
	 */
	public long getRatingId();

	/**
	 * Sets the rating ID of this rating.
	 *
	 * @param ratingId the rating ID of this rating
	 */
	public void setRatingId(long ratingId);

	/**
	 * Returns the create date of this rating.
	 *
	 * @return the create date of this rating
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this rating.
	 *
	 * @param createDate the create date of this rating
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the company ID of this rating.
	 *
	 * @return the company ID of this rating
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rating.
	 *
	 * @param companyId the company ID of this rating
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the fully qualified class name of this rating.
	 *
	 * @return the fully qualified class name of this rating
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this rating.
	 *
	 * @return the class name ID of this rating
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this rating.
	 *
	 * @param classNameId the class name ID of this rating
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this rating.
	 *
	 * @return the class pk of this rating
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this rating.
	 *
	 * @param classPK the class pk of this rating
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the score of this rating.
	 *
	 * @return the score of this rating
	 */
	public double getScore();

	/**
	 * Sets the score of this rating.
	 *
	 * @param score the score of this rating
	 */
	public void setScore(double score);

	/**
	 * Returns the comment of this rating.
	 *
	 * @return the comment of this rating
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this rating.
	 *
	 * @param comment the comment of this rating
	 */
	public void setComment(String comment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Rating rating);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Rating> toCacheModel();

	@Override
	public Rating toEscapedModel();

	@Override
	public Rating toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}