/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.social_network.sb.model.impl;

import aQute.bnd.annotation.ProviderType;

import es.aragon.base.social_network.sb.model.SocialNetwork;
import es.aragon.base.social_network.sb.service.SocialNetworkLocalServiceUtil;

/**
 * The extended model base implementation for the SocialNetwork service. Represents a row in the &quot;EAB_SN_SocialNetwork&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialNetworkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialNetworkImpl
 * @see SocialNetwork
 * @generated
 */
@ProviderType
public abstract class SocialNetworkBaseImpl extends SocialNetworkModelImpl
	implements SocialNetwork {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a social network model instance should use the {@link SocialNetwork} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SocialNetworkLocalServiceUtil.addSocialNetwork(this);
		}
		else {
			SocialNetworkLocalServiceUtil.updateSocialNetwork(this);
		}
	}
}