/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.migration.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import es.aragon.base.migration.model.ContentImage;
import es.aragon.base.migration.model.ContentImageModel;
import es.aragon.base.migration.model.ContentImageSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ContentImage service. Represents a row in the &quot;EAB_MG_ContentImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ContentImageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContentImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentImageImpl
 * @see ContentImage
 * @see ContentImageModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ContentImageModelImpl extends BaseModelImpl<ContentImage>
	implements ContentImageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a content image model instance should use the {@link ContentImage} interface instead.
	 */
	public static final String TABLE_NAME = "EAB_MG_ContentImage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "contentImageId", Types.BIGINT },
			{ "contentOriginId", Types.BIGINT },
			{ "url", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contentImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentOriginId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table EAB_MG_ContentImage (uuid_ VARCHAR(75) null,contentImageId LONG not null primary key,contentOriginId LONG,url STRING null)";
	public static final String TABLE_SQL_DROP = "drop table EAB_MG_ContentImage";
	public static final String ORDER_BY_JPQL = " ORDER BY contentImage.contentImageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY EAB_MG_ContentImage.contentImageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(es.aragon.base.migration.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.es.aragon.base.migration.model.ContentImage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(es.aragon.base.migration.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.es.aragon.base.migration.model.ContentImage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(es.aragon.base.migration.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.es.aragon.base.migration.model.ContentImage"),
			true);
	public static final long CONTENTORIGINID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long CONTENTIMAGEID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ContentImage toModel(ContentImageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ContentImage model = new ContentImageImpl();

		model.setUuid(soapModel.getUuid());
		model.setContentImageId(soapModel.getContentImageId());
		model.setContentOriginId(soapModel.getContentOriginId());
		model.setUrl(soapModel.getUrl());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ContentImage> toModels(ContentImageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ContentImage> models = new ArrayList<ContentImage>(soapModels.length);

		for (ContentImageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(es.aragon.base.migration.service.util.ServiceProps.get(
				"lock.expiration.time.es.aragon.base.migration.model.ContentImage"));

	public ContentImageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contentImageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContentImageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contentImageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContentImage.class;
	}

	@Override
	public String getModelClassName() {
		return ContentImage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("contentImageId", getContentImageId());
		attributes.put("contentOriginId", getContentOriginId());
		attributes.put("url", getUrl());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long contentImageId = (Long)attributes.get("contentImageId");

		if (contentImageId != null) {
			setContentImageId(contentImageId);
		}

		Long contentOriginId = (Long)attributes.get("contentOriginId");

		if (contentOriginId != null) {
			setContentOriginId(contentOriginId);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getContentImageId() {
		return _contentImageId;
	}

	@Override
	public void setContentImageId(long contentImageId) {
		_contentImageId = contentImageId;
	}

	@JSON
	@Override
	public long getContentOriginId() {
		return _contentOriginId;
	}

	@Override
	public void setContentOriginId(long contentOriginId) {
		_columnBitmask |= CONTENTORIGINID_COLUMN_BITMASK;

		if (!_setOriginalContentOriginId) {
			_setOriginalContentOriginId = true;

			_originalContentOriginId = _contentOriginId;
		}

		_contentOriginId = contentOriginId;
	}

	public long getOriginalContentOriginId() {
		return _originalContentOriginId;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ContentImage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContentImage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ContentImage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContentImageImpl contentImageImpl = new ContentImageImpl();

		contentImageImpl.setUuid(getUuid());
		contentImageImpl.setContentImageId(getContentImageId());
		contentImageImpl.setContentOriginId(getContentOriginId());
		contentImageImpl.setUrl(getUrl());

		contentImageImpl.resetOriginalValues();

		return contentImageImpl;
	}

	@Override
	public int compareTo(ContentImage contentImage) {
		long primaryKey = contentImage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ContentImage)) {
			return false;
		}

		ContentImage contentImage = (ContentImage)obj;

		long primaryKey = contentImage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ContentImageModelImpl contentImageModelImpl = this;

		contentImageModelImpl._originalUuid = contentImageModelImpl._uuid;

		contentImageModelImpl._originalContentOriginId = contentImageModelImpl._contentOriginId;

		contentImageModelImpl._setOriginalContentOriginId = false;

		contentImageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ContentImage> toCacheModel() {
		ContentImageCacheModel contentImageCacheModel = new ContentImageCacheModel();

		contentImageCacheModel.uuid = getUuid();

		String uuid = contentImageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contentImageCacheModel.uuid = null;
		}

		contentImageCacheModel.contentImageId = getContentImageId();

		contentImageCacheModel.contentOriginId = getContentOriginId();

		contentImageCacheModel.url = getUrl();

		String url = contentImageCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			contentImageCacheModel.url = null;
		}

		return contentImageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", contentImageId=");
		sb.append(getContentImageId());
		sb.append(", contentOriginId=");
		sb.append(getContentOriginId());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("es.aragon.base.migration.model.ContentImage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contentImageId</column-name><column-value><![CDATA[");
		sb.append(getContentImageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contentOriginId</column-name><column-value><![CDATA[");
		sb.append(getContentOriginId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ContentImage.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ContentImage.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _contentImageId;
	private long _contentOriginId;
	private long _originalContentOriginId;
	private boolean _setOriginalContentOriginId;
	private String _url;
	private long _columnBitmask;
	private ContentImage _escapedModel;
}