/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.crawler.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Page service. Represents a row in the &quot;EAB_CRAWLER_Page&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.crawler.model.impl.PageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.crawler.model.impl.PageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Page
 * @see es.aragon.base.crawler.model.impl.PageImpl
 * @see es.aragon.base.crawler.model.impl.PageModelImpl
 * @generated
 */
@ProviderType
public interface PageModel extends BaseModel<Page> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a page model instance should use the {@link Page} interface instead.
	 */

	/**
	 * Returns the primary key of this page.
	 *
	 * @return the primary key of this page
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this page.
	 *
	 * @param primaryKey the primary key of this page
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this page.
	 *
	 * @return the uuid of this page
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this page.
	 *
	 * @param uuid the uuid of this page
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the page ID of this page.
	 *
	 * @return the page ID of this page
	 */
	public long getPageId();

	/**
	 * Sets the page ID of this page.
	 *
	 * @param pageId the page ID of this page
	 */
	public void setPageId(long pageId);

	/**
	 * Returns the title of this page.
	 *
	 * @return the title of this page
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this page.
	 *
	 * @param title the title of this page
	 */
	public void setTitle(String title);

	/**
	 * Returns the content type of this page.
	 *
	 * @return the content type of this page
	 */
	@AutoEscape
	public String getContentType();

	/**
	 * Sets the content type of this page.
	 *
	 * @param contentType the content type of this page
	 */
	public void setContentType(String contentType);

	/**
	 * Returns the meta description of this page.
	 *
	 * @return the meta description of this page
	 */
	@AutoEscape
	public String getMetaDescription();

	/**
	 * Sets the meta description of this page.
	 *
	 * @param metaDescription the meta description of this page
	 */
	public void setMetaDescription(String metaDescription);

	/**
	 * Returns the meta keywords of this page.
	 *
	 * @return the meta keywords of this page
	 */
	@AutoEscape
	public String getMetaKeywords();

	/**
	 * Sets the meta keywords of this page.
	 *
	 * @param metaKeywords the meta keywords of this page
	 */
	public void setMetaKeywords(String metaKeywords);

	/**
	 * Returns the content of this page.
	 *
	 * @return the content of this page
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this page.
	 *
	 * @param content the content of this page
	 */
	public void setContent(String content);

	/**
	 * Returns the url of this page.
	 *
	 * @return the url of this page
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this page.
	 *
	 * @param url the url of this page
	 */
	public void setUrl(String url);

	/**
	 * Returns the category IDs of this page.
	 *
	 * @return the category IDs of this page
	 */
	@AutoEscape
	public String getCategoryIds();

	/**
	 * Sets the category IDs of this page.
	 *
	 * @param categoryIds the category IDs of this page
	 */
	public void setCategoryIds(String categoryIds);

	/**
	 * Returns the root page ID of this page.
	 *
	 * @return the root page ID of this page
	 */
	public long getRootPageId();

	/**
	 * Sets the root page ID of this page.
	 *
	 * @param rootPageId the root page ID of this page
	 */
	public void setRootPageId(long rootPageId);

	/**
	 * Returns the parent page ID of this page.
	 *
	 * @return the parent page ID of this page
	 */
	public long getParentPageId();

	/**
	 * Sets the parent page ID of this page.
	 *
	 * @param parentPageId the parent page ID of this page
	 */
	public void setParentPageId(long parentPageId);

	/**
	 * Returns the status of this page.
	 *
	 * @return the status of this page
	 */
	public long getStatus();

	/**
	 * Sets the status of this page.
	 *
	 * @param status the status of this page
	 */
	public void setStatus(long status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Page page);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Page> toCacheModel();

	@Override
	public Page toEscapedModel();

	@Override
	public Page toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}