/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.crawler.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RootPage service. Represents a row in the &quot;EAB_CRAWLER_RootPage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.crawler.model.impl.RootPageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.crawler.model.impl.RootPageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RootPage
 * @see es.aragon.base.crawler.model.impl.RootPageImpl
 * @see es.aragon.base.crawler.model.impl.RootPageModelImpl
 * @generated
 */
@ProviderType
public interface RootPageModel extends BaseModel<RootPage>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a root page model instance should use the {@link RootPage} interface instead.
	 */

	/**
	 * Returns the primary key of this root page.
	 *
	 * @return the primary key of this root page
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this root page.
	 *
	 * @param primaryKey the primary key of this root page
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this root page.
	 *
	 * @return the uuid of this root page
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this root page.
	 *
	 * @param uuid the uuid of this root page
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the root page ID of this root page.
	 *
	 * @return the root page ID of this root page
	 */
	public long getRootPageId();

	/**
	 * Sets the root page ID of this root page.
	 *
	 * @param rootPageId the root page ID of this root page
	 */
	public void setRootPageId(long rootPageId);

	/**
	 * Returns the group ID of this root page.
	 *
	 * @return the group ID of this root page
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this root page.
	 *
	 * @param groupId the group ID of this root page
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this root page.
	 *
	 * @return the company ID of this root page
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this root page.
	 *
	 * @param companyId the company ID of this root page
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the crawled date of this root page.
	 *
	 * @return the crawled date of this root page
	 */
	public Date getCrawledDate();

	/**
	 * Sets the crawled date of this root page.
	 *
	 * @param crawledDate the crawled date of this root page
	 */
	public void setCrawledDate(Date crawledDate);

	/**
	 * Returns the alias of this root page.
	 *
	 * @return the alias of this root page
	 */
	@AutoEscape
	public String getAlias();

	/**
	 * Sets the alias of this root page.
	 *
	 * @param alias the alias of this root page
	 */
	public void setAlias(String alias);

	/**
	 * Returns the inclusion rules of this root page.
	 *
	 * @return the inclusion rules of this root page
	 */
	@AutoEscape
	public String getInclusionRules();

	/**
	 * Sets the inclusion rules of this root page.
	 *
	 * @param inclusionRules the inclusion rules of this root page
	 */
	public void setInclusionRules(String inclusionRules);

	/**
	 * Returns the page ID of this root page.
	 *
	 * @return the page ID of this root page
	 */
	public long getPageId();

	/**
	 * Sets the page ID of this root page.
	 *
	 * @param pageId the page ID of this root page
	 */
	public void setPageId(long pageId);

	/**
	 * Returns the scheduled crawl of this root page.
	 *
	 * @return the scheduled crawl of this root page
	 */
	public boolean getScheduledCrawl();

	/**
	 * Returns <code>true</code> if this root page is scheduled crawl.
	 *
	 * @return <code>true</code> if this root page is scheduled crawl; <code>false</code> otherwise
	 */
	public boolean isScheduledCrawl();

	/**
	 * Sets whether this root page is scheduled crawl.
	 *
	 * @param scheduledCrawl the scheduled crawl of this root page
	 */
	public void setScheduledCrawl(boolean scheduledCrawl);

	/**
	 * Returns the depth of this root page.
	 *
	 * @return the depth of this root page
	 */
	public int getDepth();

	/**
	 * Sets the depth of this root page.
	 *
	 * @param depth the depth of this root page
	 */
	public void setDepth(int depth);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(RootPage rootPage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<RootPage> toCacheModel();

	@Override
	public RootPage toEscapedModel();

	@Override
	public RootPage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}