/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.categories_custom_properties.model.impl;

import aQute.bnd.annotation.ProviderType;

import es.aragon.base.categories_custom_properties.model.CustomCategoryProperty;
import es.aragon.base.categories_custom_properties.service.CustomCategoryPropertyLocalServiceUtil;

/**
 * The extended model base implementation for the CustomCategoryProperty service. Represents a row in the &quot;EAB_CCP_CustomCategoryProperty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomCategoryPropertyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomCategoryPropertyImpl
 * @see CustomCategoryProperty
 * @generated
 */
@ProviderType
public abstract class CustomCategoryPropertyBaseImpl
	extends CustomCategoryPropertyModelImpl implements CustomCategoryProperty {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom category property model instance should use the {@link CustomCategoryProperty} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CustomCategoryPropertyLocalServiceUtil.addCustomCategoryProperty(this);
		}
		else {
			CustomCategoryPropertyLocalServiceUtil.updateCustomCategoryProperty(this);
		}
	}
}