/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.migration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ContentRelated service. Represents a row in the &quot;EAB_MG_ContentRelated&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.migration.model.impl.ContentRelatedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.migration.model.impl.ContentRelatedImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentRelated
 * @see es.aragon.base.migration.model.impl.ContentRelatedImpl
 * @see es.aragon.base.migration.model.impl.ContentRelatedModelImpl
 * @generated
 */
@ProviderType
public interface ContentRelatedModel extends BaseModel<ContentRelated> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content related model instance should use the {@link ContentRelated} interface instead.
	 */

	/**
	 * Returns the primary key of this content related.
	 *
	 * @return the primary key of this content related
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content related.
	 *
	 * @param primaryKey the primary key of this content related
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this content related.
	 *
	 * @return the uuid of this content related
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this content related.
	 *
	 * @param uuid the uuid of this content related
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the content related ID of this content related.
	 *
	 * @return the content related ID of this content related
	 */
	public long getContentRelatedId();

	/**
	 * Sets the content related ID of this content related.
	 *
	 * @param contentRelatedId the content related ID of this content related
	 */
	public void setContentRelatedId(long contentRelatedId);

	/**
	 * Returns the content parent ID of this content related.
	 *
	 * @return the content parent ID of this content related
	 */
	public long getContentParentId();

	/**
	 * Sets the content parent ID of this content related.
	 *
	 * @param contentParentId the content parent ID of this content related
	 */
	public void setContentParentId(long contentParentId);

	/**
	 * Returns the content linked ID of this content related.
	 *
	 * @return the content linked ID of this content related
	 */
	public long getContentLinkedId();

	/**
	 * Sets the content linked ID of this content related.
	 *
	 * @param contentLinkedId the content linked ID of this content related
	 */
	public void setContentLinkedId(long contentLinkedId);

	/**
	 * Returns the url of this content related.
	 *
	 * @return the url of this content related
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this content related.
	 *
	 * @param url the url of this content related
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ContentRelated contentRelated);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ContentRelated> toCacheModel();

	@Override
	public ContentRelated toEscapedModel();

	@Override
	public ContentRelated toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}