/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.migration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Content service. Represents a row in the &quot;EAB_MG_Content&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.migration.model.impl.ContentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.migration.model.impl.ContentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Content
 * @see es.aragon.base.migration.model.impl.ContentImpl
 * @see es.aragon.base.migration.model.impl.ContentModelImpl
 * @generated
 */
@ProviderType
public interface ContentModel extends BaseModel<Content> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content model instance should use the {@link Content} interface instead.
	 */

	/**
	 * Returns the primary key of this content.
	 *
	 * @return the primary key of this content
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content.
	 *
	 * @param primaryKey the primary key of this content
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this content.
	 *
	 * @return the uuid of this content
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this content.
	 *
	 * @param uuid the uuid of this content
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the content ID of this content.
	 *
	 * @return the content ID of this content
	 */
	public long getContentId();

	/**
	 * Sets the content ID of this content.
	 *
	 * @param contentId the content ID of this content
	 */
	public void setContentId(long contentId);

	/**
	 * Returns the title of this content.
	 *
	 * @return the title of this content
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this content.
	 *
	 * @param title the title of this content
	 */
	public void setTitle(String title);

	/**
	 * Returns the url of this content.
	 *
	 * @return the url of this content
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this content.
	 *
	 * @param url the url of this content
	 */
	public void setUrl(String url);

	/**
	 * Returns the content type of this content.
	 *
	 * @return the content type of this content
	 */
	@AutoEscape
	public String getContentType();

	/**
	 * Sets the content type of this content.
	 *
	 * @param contentType the content type of this content
	 */
	public void setContentType(String contentType);

	/**
	 * Returns the short excerpt of this content.
	 *
	 * @return the short excerpt of this content
	 */
	@AutoEscape
	public String getShortExcerpt();

	/**
	 * Sets the short excerpt of this content.
	 *
	 * @param shortExcerpt the short excerpt of this content
	 */
	public void setShortExcerpt(String shortExcerpt);

	/**
	 * Returns the excerpt of this content.
	 *
	 * @return the excerpt of this content
	 */
	@AutoEscape
	public String getExcerpt();

	/**
	 * Sets the excerpt of this content.
	 *
	 * @param excerpt the excerpt of this content
	 */
	public void setExcerpt(String excerpt);

	/**
	 * Returns the original body hash of this content.
	 *
	 * @return the original body hash of this content
	 */
	@AutoEscape
	public String getOriginalBodyHash();

	/**
	 * Sets the original body hash of this content.
	 *
	 * @param originalBodyHash the original body hash of this content
	 */
	public void setOriginalBodyHash(String originalBodyHash);

	/**
	 * Returns the original body of this content.
	 *
	 * @return the original body of this content
	 */
	@AutoEscape
	public String getOriginalBody();

	/**
	 * Sets the original body of this content.
	 *
	 * @param originalBody the original body of this content
	 */
	public void setOriginalBody(String originalBody);

	/**
	 * Returns the area ID of this content.
	 *
	 * @return the area ID of this content
	 */
	public long getAreaId();

	/**
	 * Sets the area ID of this content.
	 *
	 * @param areaId the area ID of this content
	 */
	public void setAreaId(long areaId);

	/**
	 * Returns the action ID of this content.
	 *
	 * @return the action ID of this content
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this content.
	 *
	 * @param actionId the action ID of this content
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the status ID of this content.
	 *
	 * @return the status ID of this content
	 */
	public long getStatusId();

	/**
	 * Sets the status ID of this content.
	 *
	 * @param statusId the status ID of this content
	 */
	public void setStatusId(long statusId);

	/**
	 * Returns the template ID of this content.
	 *
	 * @return the template ID of this content
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this content.
	 *
	 * @param templateId the template ID of this content
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the tags of this content.
	 *
	 * @return the tags of this content
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this content.
	 *
	 * @param tags the tags of this content
	 */
	public void setTags(String tags);

	/**
	 * Returns the last modified user ID of this content.
	 *
	 * @return the last modified user ID of this content
	 */
	public long getLastModifiedUserId();

	/**
	 * Sets the last modified user ID of this content.
	 *
	 * @param lastModifiedUserId the last modified user ID of this content
	 */
	public void setLastModifiedUserId(long lastModifiedUserId);

	/**
	 * Returns the last modified user uuid of this content.
	 *
	 * @return the last modified user uuid of this content
	 */
	public String getLastModifiedUserUuid();

	/**
	 * Sets the last modified user uuid of this content.
	 *
	 * @param lastModifiedUserUuid the last modified user uuid of this content
	 */
	public void setLastModifiedUserUuid(String lastModifiedUserUuid);

	/**
	 * Returns the assigned user ID of this content.
	 *
	 * @return the assigned user ID of this content
	 */
	public long getAssignedUserId();

	/**
	 * Sets the assigned user ID of this content.
	 *
	 * @param assignedUserId the assigned user ID of this content
	 */
	public void setAssignedUserId(long assignedUserId);

	/**
	 * Returns the assigned user uuid of this content.
	 *
	 * @return the assigned user uuid of this content
	 */
	public String getAssignedUserUuid();

	/**
	 * Sets the assigned user uuid of this content.
	 *
	 * @param assignedUserUuid the assigned user uuid of this content
	 */
	public void setAssignedUserUuid(String assignedUserUuid);

	/**
	 * Returns the user group ID of this content.
	 *
	 * @return the user group ID of this content
	 */
	public long getUserGroupId();

	/**
	 * Sets the user group ID of this content.
	 *
	 * @param userGroupId the user group ID of this content
	 */
	public void setUserGroupId(long userGroupId);

	/**
	 * Returns the journal folder ID of this content.
	 *
	 * @return the journal folder ID of this content
	 */
	public long getJournalFolderId();

	/**
	 * Sets the journal folder ID of this content.
	 *
	 * @param journalFolderId the journal folder ID of this content
	 */
	public void setJournalFolderId(long journalFolderId);

	/**
	 * Returns the date created of this content.
	 *
	 * @return the date created of this content
	 */
	public Date getDateCreated();

	/**
	 * Sets the date created of this content.
	 *
	 * @param dateCreated the date created of this content
	 */
	public void setDateCreated(Date dateCreated);

	/**
	 * Returns the date modified of this content.
	 *
	 * @return the date modified of this content
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this content.
	 *
	 * @param dateModified the date modified of this content
	 */
	public void setDateModified(Date dateModified);

	/**
	 * Returns the comments of this content.
	 *
	 * @return the comments of this content
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this content.
	 *
	 * @param comments the comments of this content
	 */
	public void setComments(String comments);

	/**
	 * Returns the visibility of this content.
	 *
	 * @return the visibility of this content
	 */
	public int getVisibility();

	/**
	 * Sets the visibility of this content.
	 *
	 * @param visibility the visibility of this content
	 */
	public void setVisibility(int visibility);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Content content);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Content> toCacheModel();

	@Override
	public Content toEscapedModel();

	@Override
	public Content toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}