/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.migration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ContentUrl service. Represents a row in the &quot;EAB_MG_ContentUrl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.migration.model.impl.ContentUrlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.migration.model.impl.ContentUrlImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContentUrl
 * @see es.aragon.base.migration.model.impl.ContentUrlImpl
 * @see es.aragon.base.migration.model.impl.ContentUrlModelImpl
 * @generated
 */
@ProviderType
public interface ContentUrlModel extends BaseModel<ContentUrl> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a content url model instance should use the {@link ContentUrl} interface instead.
	 */

	/**
	 * Returns the primary key of this content url.
	 *
	 * @return the primary key of this content url
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this content url.
	 *
	 * @param primaryKey the primary key of this content url
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this content url.
	 *
	 * @return the uuid of this content url
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this content url.
	 *
	 * @param uuid the uuid of this content url
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the content url ID of this content url.
	 *
	 * @return the content url ID of this content url
	 */
	public long getContentUrlId();

	/**
	 * Sets the content url ID of this content url.
	 *
	 * @param contentUrlId the content url ID of this content url
	 */
	public void setContentUrlId(long contentUrlId);

	/**
	 * Returns the content origin ID of this content url.
	 *
	 * @return the content origin ID of this content url
	 */
	public long getContentOriginId();

	/**
	 * Sets the content origin ID of this content url.
	 *
	 * @param contentOriginId the content origin ID of this content url
	 */
	public void setContentOriginId(long contentOriginId);

	/**
	 * Returns the content destination ID of this content url.
	 *
	 * @return the content destination ID of this content url
	 */
	public long getContentDestinationId();

	/**
	 * Sets the content destination ID of this content url.
	 *
	 * @param contentDestinationId the content destination ID of this content url
	 */
	public void setContentDestinationId(long contentDestinationId);

	/**
	 * Returns the url origin of this content url.
	 *
	 * @return the url origin of this content url
	 */
	@AutoEscape
	public String getUrlOrigin();

	/**
	 * Sets the url origin of this content url.
	 *
	 * @param urlOrigin the url origin of this content url
	 */
	public void setUrlOrigin(String urlOrigin);

	/**
	 * Returns the url destination of this content url.
	 *
	 * @return the url destination of this content url
	 */
	@AutoEscape
	public String getUrlDestination();

	/**
	 * Sets the url destination of this content url.
	 *
	 * @param urlDestination the url destination of this content url
	 */
	public void setUrlDestination(String urlDestination);

	/**
	 * Returns the class name of this content url.
	 *
	 * @return the class name of this content url
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this content url.
	 *
	 * @param className the class name of this content url
	 */
	public void setClassName(String className);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ContentUrl contentUrl);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ContentUrl> toCacheModel();

	@Override
	public ContentUrl toEscapedModel();

	@Override
	public ContentUrl toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}