/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.aragon.base.migration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Template service. Represents a row in the &quot;EAB_MG_Template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.aragon.base.migration.model.impl.TemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.aragon.base.migration.model.impl.TemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Template
 * @see es.aragon.base.migration.model.impl.TemplateImpl
 * @see es.aragon.base.migration.model.impl.TemplateModelImpl
 * @generated
 */
@ProviderType
public interface TemplateModel extends BaseModel<Template> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a template model instance should use the {@link Template} interface instead.
	 */

	/**
	 * Returns the primary key of this template.
	 *
	 * @return the primary key of this template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this template.
	 *
	 * @param primaryKey the primary key of this template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this template.
	 *
	 * @return the uuid of this template
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this template.
	 *
	 * @param uuid the uuid of this template
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the template ID of this template.
	 *
	 * @return the template ID of this template
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this template.
	 *
	 * @param templateId the template ID of this template
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the name of this template.
	 *
	 * @return the name of this template
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this template.
	 *
	 * @param name the name of this template
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Template template);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Template> toCacheModel();

	@Override
	public Template toEscapedModel();

	@Override
	public Template toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}